### ISSUE TITLE
option to rebase and merge

### ISSUE THREAD

**Issue by jnoortheen** [koj-co/dependabot-pr-action#17]
Thanks for this GA !

One small request. 
I like to keep my VCS history clean. I have enabled rebase and merge for the PRs. When running the schedule, the dependabot PRs fail  other than the first one. 
Could you add option to rebase ?

<details><summary>traceback</summary>

```
RequestError [HttpError]: Merge commits are not allowed on this repository.
    at /home/runner/work/_actions/koj-co/dependabot-pr-action/master/node_modules/@octokit/request/dist-node/index.js:66:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at autoMerge (/home/runner/work/_actions/koj-co/dependabot-pr-action/master/dist/index.js:32:1) {
  name: 'HttpError',
  status: 405,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '151',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 13 Dec 2020 04:12:49 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '405 Method Not Allowed',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0405:4BB3:7956A0:11D7752:5FD594C1',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '993',
    'x-ratelimit-reset': '1607836368',
    'x-ratelimit-used': '7',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/nix-community/vscode-nix-ide/pulls/54/merge',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.1.2 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"commit_title":":twisted_rightwards_arrows: Merge #54 (chore(deps): bump ini from 1.3.5 to 1.3.8)"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/pulls#merge-a-pull-request'
}
```

</details>

**Comment by pabio-escobar** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by pabio-escobar** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
